#!/bin/bash
# ##################################################
# NAME:
#   docker-build-dpp
# DESCRIPTION:
#   Builds Decoder++ container
# AUTHOR:
#   bytebutcher
# ##################################################
cd ..

if [ $# -eq 0 ] ; then
    echo "usage: $(basename $0) qtlib=qt5|qt6" >&2
    exit 1
fi

qtlib="${1}"
if [[ "${qtlib}" != "qt5" ]] && [[ "${qtlib}" != "qt6" ]] ; then
	echo "ERROR: Invalid qtlib argument! Valid options are: qt5|qt6" >&2
	exit 1
fi

if ! [ -f "setup.py" ] ; then
	echo "ERROR: Missing required setup.py in source code repository!" >&2
	exit 1
fi

version="$(python3 setup.py --version)"
docker build -t bytebutcher/decoder-plus-plus-${qtlib}:${version} -f ./docker/${qtlib}/Dockerfile .
